// Code generated by onyx init; DO NOT EDIT.
// Generated at: 2026-01-20T00:10:35Z

package codegen

//go:generate onyx gen --go --source file --schema ./api/onyx.schema.json --out ./gen/onyx --package onyx
