// Code generated by onyx-go init; DO NOT EDIT.
// Generated at: 2026-01-19T03:16:23Z

package codegen

//go:generate onyx-go gen --source file --schema ./api/onyx.schema.json --out ./gen/onyx --package onyx
