// Code generated by onyx-gen-go; DO NOT EDIT.

package onyxclient

import (
	"time"
)

var Tables = struct {
	AuditLog       string
	Permission     string
	Role           string
	RolePermission string
	User           string
	UserProfile    string
	UserRole       string
}{
	AuditLog:       "AuditLog",
	Permission:     "Permission",
	Role:           "Role",
	RolePermission: "RolePermission",
	User:           "User",
	UserProfile:    "UserProfile",
	UserRole:       "UserRole",
}

var Resolvers = map[string][]string{
	"Role":           {"permissions", "rolePermissions"},
	"RolePermission": {"permission", "role"},
	"User":           {"profile", "roles", "userRoles"},
	"UserRole":       {"role"},
}

type AuditLog struct {
	Action       *string        `json:"action,omitempty"`
	ActorId      *string        `json:"actorId,omitempty"`
	Changes      map[string]any `json:"changes,omitempty"`
	DateTime     time.Time      `json:"dateTime,omitempty"`
	ErrorCode    *string        `json:"errorCode,omitempty"`
	ErrorMessage *string        `json:"errorMessage,omitempty"`
	Id           string         `json:"id,omitempty"`
	Metadata     map[string]any `json:"metadata,omitempty"`
	RequestId    *string        `json:"requestId,omitempty"`
	Resource     *string        `json:"resource,omitempty"`
	Status       *string        `json:"status,omitempty"`
	TargetId     *string        `json:"targetId,omitempty"`
	TenantId     *string        `json:"tenantId,omitempty"`
}

type Permission struct {
	CreatedAt   time.Time  `json:"createdAt,omitempty"`
	DeletedAt   *time.Time `json:"deletedAt,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          string     `json:"id,omitempty"`
	Name        string     `json:"name,omitempty"`
	UpdatedAt   time.Time  `json:"updatedAt,omitempty"`
}

type Role struct {
	CreatedAt       time.Time  `json:"createdAt,omitempty"`
	DeletedAt       *time.Time `json:"deletedAt,omitempty"`
	Description     *string    `json:"description,omitempty"`
	Id              string     `json:"id,omitempty"`
	IsSystem        bool       `json:"isSystem,omitempty"`
	Name            string     `json:"name,omitempty"`
	UpdatedAt       time.Time  `json:"updatedAt,omitempty"`
	Permissions     any        `json:"permissions,omitempty"`
	RolePermissions any        `json:"rolePermissions,omitempty"`
}

type RolePermission struct {
	CreatedAt    time.Time `json:"createdAt,omitempty"`
	Id           string    `json:"id,omitempty"`
	PermissionId string    `json:"permissionId,omitempty"`
	RoleId       string    `json:"roleId,omitempty"`
	Permission   any       `json:"permission,omitempty"`
	Role         any       `json:"role,omitempty"`
}

type User struct {
	Asdf        string     `json:"asdf,omitempty"`
	CreatedAt   time.Time  `json:"createdAt,omitempty"`
	DeletedAt   *time.Time `json:"deletedAt,omitempty"`
	Email       string     `json:"email,omitempty"`
	Id          string     `json:"id,omitempty"`
	IsActive    bool       `json:"isActive,omitempty"`
	LastLoginAt *time.Time `json:"lastLoginAt,omitempty"`
	UpdatedAt   time.Time  `json:"updatedAt,omitempty"`
	Username    string     `json:"username,omitempty"`
	Profile     any        `json:"profile,omitempty"`
	Roles       any        `json:"roles,omitempty"`
	UserRoles   any        `json:"userRoles,omitempty"`
}

type UserProfile struct {
	Address   map[string]any `json:"address,omitempty"`
	Age       *int64         `json:"age,omitempty"`
	AvatarUrl *string        `json:"avatarUrl,omitempty"`
	Bio       *string        `json:"bio,omitempty"`
	CreatedAt time.Time      `json:"createdAt,omitempty"`
	DeletedAt *time.Time     `json:"deletedAt,omitempty"`
	FirstName string         `json:"firstName,omitempty"`
	Id        string         `json:"id,omitempty"`
	LastName  string         `json:"lastName,omitempty"`
	Phone     *string        `json:"phone,omitempty"`
	UpdatedAt *time.Time     `json:"updatedAt,omitempty"`
	UserId    string         `json:"userId,omitempty"`
}

type UserRole struct {
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Id        string    `json:"id,omitempty"`
	RoleId    string    `json:"roleId,omitempty"`
	UserId    string    `json:"userId,omitempty"`
	Role      any       `json:"role,omitempty"`
}
